apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-web
  labels:
    app: queries-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries-web
  template:
    metadata:
      labels:
        app: queries-web
    spec:
      containers:
      - name: queries-web
        image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/queries-web:IMAGE_VERSION
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_HOST
          value: "http://queries-api-svc:80"
---
apiVersion: v1
kind: Service
metadata:
  name: queries-web-svc
spec:
  selector:
    app: queries-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
